name: Teslon Incorporation
favicon: null
layout_spectrum: 0.8296145363710821
typography_spectrum: 0.9737664060667157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.028776451013982296
  lightness: 0.8615111210383475
  saturation: 0.7802791746798903
  rhythmicContrast: 0.5670868179295212
purpose: []
